name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependecies
      run: sudo apt install libcurl3-gnutls-dev
    - name: make
      run: make
    - name: make test
      run: make test
